development:
  adapter: mysql2
  encoding: utf8
  database: cwf_development
  pool: 5
  timeout: 5000
  username: root
  password: password

test: &test
  adapter: mysql2
  encoding: utf8
  database: cwf_test
  pool: 5
  timeout: 5000
  username: root
  password: password
